### ISSUE TITLE
Menu issue after installing this package 

### ISSUE THREAD

**Issue by ObaydaAlesawi** [kiritokatklian/nova-permission#18]
After installing this package, all menus can't be clicked and this error occurred
(in promise) TypeError: Cannot read properties of undefined (reading 'toString')
![image](https://user-images.githubusercontent.com/32073999/171996477-20b34939-34cb-478b-8ebd-2efcc8aaa1a6.png)

**Comment by kiritokatklian** [comment]
@Algeneralo
My guess is it's either caused by a conflict with another package or because of a recent Nova update. Can you please try disabling other packages and let me know which one is causing the conflict, if any?

Also what Nova version are you using?

**Comment by felly** [comment]
I don't know why this error occurs, but at least for me it works again after removing the translation in the group function:

```php
public static function group()
{
    // return __('nova-permission-tool::navigation.sidebar-label');
    return 'Roles & Permissions';
}
```

**Comment by ahmedmaazin** [comment]
Laravel Framework: `9.17.0`
Laravel Nova: `4.8.1`

I've started testing this package and can confirm this issue does not happen to me. Maybe I'm missing the issue defined here or it's no longer an issue? 😄 

btw: @kiritokatklian thanks a lot for this fork.
