### ISSUE TITLE
No data permissions

### ISSUE THREAD

**Issue by KickSchutte67** [kiritokatklian/nova-permission#20]
Hey! I am currently using this package to represent any permissions attached to a user.

On localhost, the permissions are visible and editable.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/31417270/185971829-081609c1-4203-4c9f-81da-2dccc9def89d.png">

 When I am deploying my localhost to a dev environment, the `PermissionBooleanGroup` gives me a "No Data".

<img width="678" alt="image" src="https://user-images.githubusercontent.com/31417270/185971936-770777f4-f7df-4852-974a-f5c209c19e06.png">

Do you have any idea what is going wrong here?

**Comment by kiritokatklian** [comment]
My guess is that the permissions aren't being fetched from the database. Can you see if the permissions being sent via the network inspector?

**Comment by kiritokatklian** [comment]
Look at he response of `784?relationshipType=` (third one from the top). It should contain a JSON of `resources -> fields -> [field of permissions] -> value`.

**Comment by kiritokatklian** [comment]
Yeah, it's this one. The value key has an empty array, so it's not fetching the permissions from the database.

Does the main permissions index page load the permissions?
