### ISSUE TITLE
Inertia issue after package installation

### ISSUE THREAD

**Issue by gaetan547** [kiritokatklian/nova-permission#27]
Hello,

After the installation of the package the following error occurs when clicking on a button or link in Nova (so it isn't possible to do anything) : "All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.".

We are using the newest version of nova and of the package, php 8.2 and spatie/laravel-permission ^5.8. No other nova packages are installed.

Any idea how we could resolve this?

Thank you in advance!

**Comment by kiritokatklian** [comment]
Hey @gaetan547 was this fixed or are you still experiencing this issue?

I'm also using the latest version of Nova, but I can't reproduce this issue, so it's difficult to debug. My guess would be CORS related issue or something network related preventing Inertia from receiving the expected response. If you still have this issue, can you check the Network tab in your browser's console to see what response is being received?
